# Site settings
title: KeizerDev
email: robertjankeizer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the blog official (programming) blog of Robert-Jan Keizer also known as KeizerDev.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.keizerdev.net" # the base hostname & protocol for your site
twitter_username: KeizerDev
github_username:  KeizerDev
permalink: /blog/:title

# Build settings
markdown: kramdown
